name: tellonaut
description: Teelo drone control.
version: 1.0.0+1

environment:
  sdk: '^3.7.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
